language: node_js
node_js:
- 10.15.3
before_install:
- openssl aes-256-cbc -K $encrypted_185e04c5f303_key -iv $encrypted_185e04c5f303_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 39.107.85.46\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install: npm install --registry=https://registry.npm.taobao.org
script: npx mocha test
after_success:
- ssh 'root@39.107.85.46' 'cd /root/.nvm/webServer && git pull'
- ssh 'root@39.107.85.46' 'cd /root/.nvm/webServer && npm install --registry=https://registry.npm.taobao.org'
- ssh 'root@39.107.85.46' 'cd /root/.nvm/webServer && SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ npm install node-sass'
- ssh 'root@39.107.85.46' 'cd /root/.nvm/webServer && npm run dev'
